name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    container:
      image: elixir:1.10.3

    services:
      db:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Install hex
      run: mix local.hex --force
    - name: Install dependencies
      run: mix deps.get
    - name: Install rebar
      run: mix local.rebar --force
    - name: Run tests
      run: mix test
    - name: Check Formatting
      run: mix format --check-formatted
    - name: Run Credo
      run: mix credo --strict
